# Generated by Django 6.0.1 on 2026-01-20 23:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Kategoriya nomi"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Tavsif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ism")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Familiya"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami to'g'ri formatda bo'lishi kerak.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Telefon raqami",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="booking.category",
                        verbose_name="Kategoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shifokor",
                "verbose_name_plural": "Shifokorlar",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_first_name",
                    models.CharField(max_length=100, verbose_name="Bemor ismi"),
                ),
                (
                    "patient_last_name",
                    models.CharField(max_length=100, verbose_name="Bemor familiyasi"),
                ),
                (
                    "patient_phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Telefon raqami to'g'ri formatda bo'lishi kerak.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Bemor telefon raqami",
                    ),
                ),
                (
                    "queue_number",
                    models.PositiveIntegerField(verbose_name="Navbat raqami"),
                ),
                (
                    "qr_code_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="qr_codes/",
                        verbose_name="QR kod rasmi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="booking.doctor",
                        verbose_name="Shifokor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Navbat",
                "verbose_name_plural": "Navbatlar",
                "ordering": ["-created_at"],
            },
        ),
    ]
